name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup entorno de desarrollo
        uses: ./.github/actions/setup-dev-env
        with:
          message: "¡Entorno de desarrollo preparado con éxito!"
      #- name: Dar permisos de ejecución
        #run: |
          #chmod +x script.sh
          #./script.sh
      #- name: Setup Node.js environment
        #uses: actions/setup-node@v4.4.0
        #with:
          #node-version: latest
      - name: Verificar Node
        run: node -v