name: Deploy server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second-jobs:
  if: ${{ github.event_name == 'push' }}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Este workflow fue ejecutado en la rama ${{ github.ref }}"