name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Dar permisos de ejecución
        run: |
          chmod +x script.sh
          ./script.sh        